### ISSUE TITLE
create 3 random pets have one output give all three pet names (use for each)

### ISSUE THREAD

**Issue by OGNav** [Rayhaan10/rayhaan-terraform-session-three#10]

**Comment by OGNav** [comment]
this still needs to use a variable - and the outputs should only have the id

**Comment by Rayhaan10** [comment]
let me know if the new way is correct please

**Comment by OGNav** [comment]
this is still incorrect

**Comment by salimkapadia** [comment]
@NavidS987 maybe as par to the issue put the desired output?

**Comment by OGNav** [comment]
I did. It is in the comment for when the issue was reopened.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OGNav** [comment]
The output was clarified in the comment of the git issue to only have the id of each pet.
This is the current output –



random_name = {

  "morpheus" = {

    "id" = "morpheus-thorough-monitor"

    "keepers" = tomap(null) /* of string */

    "length" = 2

    "prefix" = "morpheus"

    "separator" = "-"

  }

  "neo" = {

    "id" = "neo-boss-hedgehog"

    "keepers" = tomap(null) /* of string */

    "length" = 2

    "prefix" = "neo"

    "separator" = "-"

  }

  "trinity" = {

    "id" = "trinity-awaited-ghost"

    "keepers" = tomap(null) /* of string */

    "length" = 2

    "prefix" = "trinity"

    "separator" = "-"

  }

}

random_pet_id = [

  {

    "morpheus" = {

      "id" = "morpheus-thorough-monitor"

      "keepers" = tomap(null) /* of string */

      "length" = 2

      "prefix" = "morpheus"

      "separator" = "-"

    }

    "neo" = {

      "id" = "neo-boss-hedgehog"

      "keepers" = tomap(null) /* of string */

      "length" = 2

      "prefix" = "neo"

      "separator" = "-"

    }

    "trinity" = {

      "id" = "trinity-awaited-ghost"

      "keepers" = tomap(null) /* of string */

      "length" = 2

      "prefix" = "trinity"

      "separator" = "-"

    }

  },

]


From: Navid S ***@***.***>
Date: Monday, May 17, 2021 at 6:32 AM
To: Rayhaan10/rayhaan-terraform-session-three ***@***.***>, Rayhaan10/rayhaan-terraform-session-three ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [Rayhaan10/rayhaan-terraform-session-three] create 3 random pets have one output give all three pet names (use for each) (#10)
I did. It is in the comment for when the issue was reopened.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OGNav** [comment]
From: Navid S ***@***.***>
Date: Monday, May 17, 2021 at 7:06 AM
To: Rayhaan10/rayhaan-terraform-session-three ***@***.***>, Rayhaan10/rayhaan-terraform-session-three ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [Rayhaan10/rayhaan-terraform-session-three] create 3 random pets have one output give all three pet names (use for each) (#10)
The output was clarified in the comment of the git issue to only have the id of each pet.
This is the current output –



random_name = {

  "morpheus" = {

    "id" = "morpheus-thorough-monitor"

    "keepers" = tomap(null) /* of string */

    "length" = 2

    "prefix" = "morpheus"

    "separator" = "-"

  }

  "neo" = {

    "id" = "neo-boss-hedgehog"

    "keepers" = tomap(null) /* of string */

    "length" = 2

    "prefix" = "neo"

    "separator" = "-"

  }

  "trinity" = {

    "id" = "trinity-awaited-ghost"

    "keepers" = tomap(null) /* of string */

    "length" = 2

    "prefix" = "trinity"

    "separator" = "-"

  }

}

random_pet_id = [

  {

    "morpheus" = {

      "id" = "morpheus-thorough-monitor"

      "keepers" = tomap(null) /* of string */

      "length" = 2

      "prefix" = "morpheus"

      "separator" = "-"

    }

    "neo" = {

      "id" = "neo-boss-hedgehog"

      "keepers" = tomap(null) /* of string */

      "length" = 2

      "prefix" = "neo"

      "separator" = "-"

    }

    "trinity" = {

      "id" = "trinity-awaited-ghost"

      "keepers" = tomap(null) /* of string */

      "length" = 2

      "prefix" = "trinity"

      "separator" = "-"

    }

  },

]


From: Navid S ***@***.***>
Date: Monday, May 17, 2021 at 6:32 AM
To: Rayhaan10/rayhaan-terraform-session-three ***@***.***>, Rayhaan10/rayhaan-terraform-session-three ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [Rayhaan10/rayhaan-terraform-session-three] create 3 random pets have one output give all three pet names (use for each) (#10)
I did. It is in the comment for when the issue was reopened.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
